quarkus.datasource.db-kind=postgresql


quarkus.flyway.migrate-at-start=true
# Use 'clean-at-start' ONLY in dev mode to reset dummy data
%dev.quarkus.flyway.clean-at-start=false

%dev.quarkus.datasource.dev-ui.allow-sql=true
