quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=validate

quarkus.flyway.migrate-at-start=true
# Use 'clean-at-start' ONLY in dev mode to reset dummy data
%dev.quarkus.flyway.clean-at-start=true

